name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      VERSION: '3.2.3'
      SERVERPOD_PASSWORD_database: 'RRCrie_TBrOnFLZZ6BvAL871MmFc4Qh4'
      SERVERPOD_PASSWORD_redis: 'HMTQM0DVkZvw3O42zrio8IW3SxRizwCq'
      # Docker Compose Environment Variables
      POSTGRES_PASSWORD: 'NVzX6QvUntWmj_BlbEo0M-TNjQITli2C'
      POSTGRES_TEST_PASSWORD: 'RRCrie_TBrOnFLZZ6BvAL871MmFc4Qh4'
      REDIS_PASSWORD: 'd0XDjLDf5bKqYyY05vW7SBzVzZNq0czW'
      REDIS_TEST_PASSWORD: 'HMTQM0DVkZvw3O42zrio8IW3SxRizwCq'

    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.8'

      - name: Start containers
        working-directory: lifeflow_butler_server
        run: docker compose up --build -d

      - name: Install dependencies
        working-directory: lifeflow_butler_server
        run: dart pub get

      - name: Install Serverpod CLI
        working-directory: lifeflow_butler_server
        run: dart pub global activate serverpod_cli $VERSION

      - name: Run Serverpod generator
        working-directory: lifeflow_butler_server
        run: serverpod generate

      - name: Run tests
        working-directory: lifeflow_butler_server
        run: dart test

      - name: Stop containers
        if: always()
        working-directory: lifeflow_butler_server
        run: docker compose down -v
